### create a pokemon

POST http://localhost:3001/api/pokemons
Content-Type: application/json

{
    "name":"squarelix",
    "classes":["bug"],
    "attack":30,
    "defense":20,
    "specialAttack":12,
    "specialDefense":5,
    "health":10,
    "speed":8,
    "picture":"algo"
}

### fetch api pokemons

GET http://localhost:3001/api/p-data

{}

### get all stored pokemons

GET http://localhost:3001/api/pokemons

### get all pokemons by search in name
GET http://localhost:3001/api/pokemons?page=1

### get all pokemons by search and order ASC
GET http://localhost:3001/api/pokemons?search=&type=&sorting=&sortColumn=&origin=&page=1

### get all the types
GET http://localhost:3001/api/t-data

### lisst types
GET http://localhost:3001/api/types?search=&type=&sorting=&sortColumn=&origin=&page=1