### create a pokemon

POST http://localhost:3001/api/pokemons
Content-Type: application/json

{
    "id":"01c",
    "name":"squarol",
    "classes":["bug"],
    "attack":10,
    "defense":10,
    "specialAttack":5,
    "specialDefense":5,
    "health":10,
    "speed":8,
    "origin":"custom"
}

### fetch api pokemons

GET http://localhost:3001/api/p-data

{}

### get all stored pokemons

GET http://localhost:3001/api/pokemons

### get all pokemons by search in name
GET http://localhost:3001/api/pokemons?search=

### get all pokemons by search and order ASC
GET http://localhost:3001/api/pokemons?search=ch&type=flying&sorting=&sortColumn=&origin=api

### get all the types
GET http://localhost:3001/api/t-data